### PR TITLE
Build pages, noreferrer, make TTS default

### PR DESCRIPTION
**Pull request by joshsymonds**
Not sure if you want to accept this but I figured I'd give it a go!

These changes:

1. Make GitHub Pages build so this fork can be accessed from the Internet.
2. Adds a `no-referrer` header so TTS works from anywhere.
3. Makes TTS and Text the default output for Cacbot.

### CODE REVIEW

**Comment by SiliconExarch** [comment]
How extensively have you tested this? In my testing, no-referrer alone wasn't enough for the TTS to work in a regular CEF browser context with an empty cache due to the same origin policy which is enforced in the HTTP response headers. Hence settling on making this fork which I use together with my own OverlayPlugin build which has web security disabled. For obvious reasons I wouldn't recommend using such a build to access overlays from the internet and this is also why I didn't bother enabling GitHub Pages.

**Comment by joshsymonds** [comment]
@SiliconExarch I'm using my fork right now with [IINACT](https://www.iinact.com/) and [Lmeter](https://github.com/joshua-software-dev/LMeter). I'm bringing my own Chromium in Linux so I have no idea how well this would work on Windows, but in Linux at least it works flawlessly and plays Google Translate API voices properly.

**Comment by joshsymonds** [comment]
If you'd like to know more or discuss this the Lmeter/IINACT Discord is at https://discord.gg/3Xk4SaC9. I have the same username there.

**Comment by SiliconExarch** [comment]
Ah, that's interesting. It seems that Lmeter is only using CefSharp to retrieve the HTML source so it's unaffected by the web security on the TTS API. 

I've been looking for an excuse to ditch ACT so I'll take another look at the weekend.

Thanks for the contribution 😄

**Comment by joshsymonds** [comment]
In Linux, you can bring your own Chromium; but if you do you need to start it with all kinds of security-bypassing flags to get this to work. But it works great there too!

I have not actually tested this in Windows so I have no idea if TotallyNotCef bypasses the security requirements as well.

**Pull request merged**
